# Generated by Django 3.0.8 on 2020-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='ProfilePicture/default.jpg', upload_to='ProfilePicture/'),
        ),
    ]
